docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

docker_min_version: "24.0.0"
firewall_zone: "public"

docker_swarm_tcp_ports:
  - 2377
  - 7946
  - 80
  - 443
  - 10050
  - 10051
  - 10052

docker_swarm_udp_ports:
  - 2377
  - 7946
  - 4789
  - 5000

zabbix_directories:
  - /data/zabbix-prod/zabbix-server/alertscripts
  - /data/zabbix-prod/zabbix-server/externalscripts
  - /data/zabbix-prod/zabbix-proxy/externalscripts
  - /data/grafana-prod/data
  - /data/zabbix-prod/postgres/data

# ALTERAR A VERSAO DO ZABBIX E A URL DE ACESSO AO AMBIENTE DO ZABBIX
zabbix_image_version: "latest"
grafana_image_version: "latest"
zabbix_domain: "exemplo.com.br"
zabbix_stack_name: "zbx-swarm"
timescaledb_image: "timescale/timescaledb:latest-pg16"
db_max_connections: 200
proxy_count: 1
proxy_base_port: 10030
proxy_hostname_prefix: "ZBXSWARNPRX"
cleanup_clone_directory: false
force_hash_check: false
docker_compose_files:
  - "{{ clone_directory }}/docker-compose.traefik.yaml"
  - "{{ clone_directory }}/docker-compose.prod.yaml"

clone_directory: "/data/zbx-files"
